# Generated by Django 4.2.1 on 2023-05-24 06:05

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created At"
                    ),
                ),
                (
                    "job_status",
                    models.CharField(
                        choices=[
                            ("Review", "Review"),
                            ("Running", "Running"),
                            ("Finished", "Finished"),
                            ("Suspended", "Suspended"),
                        ],
                        default="Review",
                        max_length=9,
                    ),
                ),
                ("job_title", models.CharField(max_length=120)),
                ("job_description", models.TextField(max_length=99000)),
                ("job_apply_url", models.CharField(max_length=120)),
                ("job_primary_tag", models.CharField(max_length=50)),
                (
                    "job_tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            blank=True, max_length=50, null=True
                        ),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "job_locations",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            blank=True, max_length=50, null=True
                        ),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                ("job_type", models.CharField(max_length=20)),
                ("job_workspace_type", models.CharField(max_length=20)),
                ("job_posted_at", models.CharField(max_length=20)),
                ("job_salary", models.CharField(max_length=20)),
                ("featured", models.CharField(blank=True, max_length=7, null=True)),
                ("email_blasted", models.BooleanField(default=False)),
                ("is_featured", models.BooleanField(default=False)),
                ("post_price", models.CharField(blank=True, max_length=20, null=True)),
                ("post_note", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "post_invoice_name",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    "post_invoice_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "post_invoice_email",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                ("client_name", models.CharField(blank=True, max_length=80, null=True)),
                (
                    "client_contact",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "client_website",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                ("logo", models.ImageField(blank=True, null=True, upload_to="logos/")),
                (
                    "posted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Post",
                        to="authentication.client",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
