# Generated by Django 4.2.1 on 2023-05-24 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Experience",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("start_date", models.CharField(max_length=50)),
                ("end_date", models.CharField(max_length=50)),
                ("currently_working", models.BooleanField(default=False)),
                ("experience_title", models.CharField(max_length=120)),
                ("experience_company", models.CharField(max_length=120)),
                (
                    "experience_details",
                    models.TextField(blank=True, max_length=1000, null=True),
                ),
                ("experience_created", models.DateTimeField(auto_now_add=True)),
                (
                    "experience_for",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Experience",
                        to="authentication.talent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("education_school", models.CharField(max_length=120)),
                ("education_level", models.CharField(max_length=120)),
                ("education_field", models.CharField(max_length=120)),
                ("start_date", models.CharField(max_length=50)),
                ("end_date", models.CharField(max_length=50)),
                ("education_created", models.DateTimeField(auto_now_add=True)),
                (
                    "education_for",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Education",
                        to="authentication.talent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("certificate_name", models.CharField(max_length=120)),
                ("issue_date", models.CharField(max_length=50)),
                ("expiration_date", models.CharField(max_length=50)),
                ("issuing_organization", models.CharField(max_length=120)),
                ("certificate_created", models.DateTimeField(auto_now_add=True)),
                (
                    "certificate_for",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Certificate",
                        to="authentication.talent",
                    ),
                ),
            ],
        ),
    ]
