# Generated by Django 4.2.1 on 2023-05-24 06:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Subscriber",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "subscribed_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Subscribed At"
                    ),
                ),
                ("email", models.EmailField(max_length=150, unique=True)),
            ],
        ),
    ]
